In [24]:

import scipy.io as sio
import pandas as pd
import numpy as np
import pandas as pd



data = sio.loadmat('Oxford_Battery_Degradation_Dataset_1.mat')
data.keys()

data['Cell1'][0][0].dtype.names


rows = []
q = []
v = []
t = []
T = []
cell_id = []
phase_name = []
cycle_name = []

for i in range(7,9):
        cell= data['Cell'+str(i)][0][0]
    
    

    
        cycle_names = cell.dtype.names
        
        for cycle in cycle_names:
            cycle_data = cell[cycle][0][0]
            phase_names = cycle_data.dtype.names
            for phase in phase_names:
                phase_data = cycle_data[phase][0][0]
                for j in range(len(phase_data['q'])):
                    q.append(phase_data['q'][j][0])
                    v.append(phase_data['v'][j][0])
                    t.append(phase_data['t'][j][0])
                    T.append(phase_data['T'][j][0])
                    cell_id.append(i)
                    phase_name.append(phase)
                    cycle_name.append(cycle)







    




df = pd.DataFrame({
    'cell_id': cell_id,
    'cycle': cycle_name,
    'phase': phase_name,
    'charge': q,
    'time': t,
    'temperature': T,
    'voltage': v

}) 



features = df.groupby(["cycle", "cell_id"]).agg({
    "voltage": ["mean","std","max","min"],
    "temperature": ["mean","max"],
    "charge": ["max","min"],
    "time": ["max","min"]
})
features.columns = ['_'.join(col) for col in features.columns]
features

                 voltage_mean  voltage_std  voltage_max  voltage_min  \
cycle   cell_id
cyc0000 7            3.780611     0.236423     4.200016     2.699889
        8            3.780142     0.235713     4.199925     2.700006
cyc0100 7            3.781310     0.236284     4.199976     2.699889
        8            3.780954     0.236011     4.200045     2.699685
cyc0200 7            3.781871     0.236092     4.200016     2.700049
...                       ...          ...          ...          ...
cyc7900 8            3.806715     0.228506     4.200051     2.699931
cyc8000 7            3.803711     0.227929     4.200182     2.700055
        8            3.809843     0.225105     4.199971     2.699971
cyc8100 7            3.802249     0.230124     4.200022     2.700015
        8            3.807207     0.228295     4.199891     2.699971

                 temperature_mean  temperature_max  charge_max  charge_min  \
cycle   cell_id
cyc0000 7               40.701409        41.959953  736.154132 -730.708523
        8               40.001219        41.466637  736.965950 -727.527951
cyc0100 7               40.754810        42.022324  730.088486 -725.622450
        8               40.037383        41.529045  730.068253 -724.361775
cyc0200 7               40.753125        42.009857  726.874376 -722.198288
...                           ...              ...         ...         ...
cyc7900 8               39.938754        41.728703  573.768344 -571.643579
cyc8000 7               40.702016        42.683468  594.678431 -592.355529
        8               39.938613        41.841015  573.629564 -570.896403
cyc8100 7               40.740380        42.446453  593.100934 -591.402253
        8               39.919358        41.678761  571.523747 -569.352707

                      time_max       time_min
cycle   cell_id
cyc0000 7        735956.787089  735954.817348
        8        735956.787527  735954.816280
cyc0100 7        735963.928429  735961.970939
        8        735963.926857  735961.966260
cyc0200 7        735971.062060  735969.112122
...                        ...            ...
cyc7900 8        736579.931370  736578.303070
cyc8000 7        736588.295431  736586.621785
        8        736588.250764  736586.622522
cyc8100 7        736595.154703  736593.483990
        8        736595.055420  736593.431805

[153 rows x 10 columns]

In [25]:
features['capacity'] = features['charge_max'] - features['charge_min']

In [26]:
features

                 voltage_mean  voltage_std  voltage_max  voltage_min  \
cycle   cell_id
cyc0000 7            3.780611     0.236423     4.200016     2.699889
        8            3.780142     0.235713     4.199925     2.700006
cyc0100 7            3.781310     0.236284     4.199976     2.699889
        8            3.780954     0.236011     4.200045     2.699685
cyc0200 7            3.781871     0.236092     4.200016     2.700049
...                       ...          ...          ...          ...
cyc7900 8            3.806715     0.228506     4.200051     2.699931
cyc8000 7            3.803711     0.227929     4.200182     2.700055
        8            3.809843     0.225105     4.199971     2.699971
cyc8100 7            3.802249     0.230124     4.200022     2.700015
        8            3.807207     0.228295     4.199891     2.699971

                 temperature_mean  temperature_max  charge_max  charge_min  \
cycle   cell_id
cyc0000 7               40.701409        41.959953  736.154132 -730.708523
        8               40.001219        41.466637  736.965950 -727.527951
cyc0100 7               40.754810        42.022324  730.088486 -725.622450
        8               40.037383        41.529045  730.068253 -724.361775
cyc0200 7               40.753125        42.009857  726.874376 -722.198288
...                           ...              ...         ...         ...
cyc7900 8               39.938754        41.728703  573.768344 -571.643579
cyc8000 7               40.702016        42.683468  594.678431 -592.355529
        8               39.938613        41.841015  573.629564 -570.896403
cyc8100 7               40.740380        42.446453  593.100934 -591.402253
        8               39.919358        41.678761  571.523747 -569.352707

                      time_max       time_min     capacity
cycle   cell_id
cyc0000 7        735956.787089  735954.817348  1466.862655
        8        735956.787527  735954.816280  1464.493901
cyc0100 7        735963.928429  735961.970939  1455.710936
        8        735963.926857  735961.966260  1454.430029
cyc0200 7        735971.062060  735969.112122  1449.072664
...                        ...            ...          ...
cyc7900 8        736579.931370  736578.303070  1145.411923
cyc8000 7        736588.295431  736586.621785  1187.033960
        8        736588.250764  736586.622522  1144.525966
cyc8100 7        736595.154703  736593.483990  1184.503186
        8        736595.055420  736593.431805  1140.876455

[153 rows x 11 columns]

In [27]:
features.drop(columns = ["charge_min"])

                 voltage_mean  voltage_std  voltage_max  voltage_min  \
cycle   cell_id
cyc0000 7            3.780611     0.236423     4.200016     2.699889
        8            3.780142     0.235713     4.199925     2.700006
cyc0100 7            3.781310     0.236284     4.199976     2.699889
        8            3.780954     0.236011     4.200045     2.699685
cyc0200 7            3.781871     0.236092     4.200016     2.700049
...                       ...          ...          ...          ...
cyc7900 8            3.806715     0.228506     4.200051     2.699931
cyc8000 7            3.803711     0.227929     4.200182     2.700055
        8            3.809843     0.225105     4.199971     2.699971
cyc8100 7            3.802249     0.230124     4.200022     2.700015
        8            3.807207     0.228295     4.199891     2.699971

                 temperature_mean  temperature_max  charge_max       time_max  \
cycle   cell_id
cyc0000 7               40.701409        41.959953  736.154132  735956.787089
        8               40.001219        41.466637  736.965950  735956.787527
cyc0100 7               40.754810        42.022324  730.088486  735963.928429
        8               40.037383        41.529045  730.068253  735963.926857
cyc0200 7               40.753125        42.009857  726.874376  735971.062060
...                           ...              ...         ...            ...
cyc7900 8               39.938754        41.728703  573.768344  736579.931370
cyc8000 7               40.702016        42.683468  594.678431  736588.295431
        8               39.938613        41.841015  573.629564  736588.250764
cyc8100 7               40.740380        42.446453  593.100934  736595.154703
        8               39.919358        41.678761  571.523747  736595.055420

                      time_min     capacity
cycle   cell_id
cyc0000 7        735954.817348  1466.862655
        8        735954.816280  1464.493901
cyc0100 7        735961.970939  1455.710936
        8        735961.966260  1454.430029
cyc0200 7        735969.112122  1449.072664
...                        ...          ...
cyc7900 8        736578.303070  1145.411923
cyc8000 7        736586.621785  1187.033960
        8        736586.622522  1144.525966
cyc8100 7        736593.483990  1184.503186
        8        736593.431805  1140.876455

[153 rows x 10 columns]

In [28]:
features['v_range'] = features['voltage_max'] - features['voltage_min']

In [29]:
features

                 voltage_mean  voltage_std  voltage_max  voltage_min  \
cycle   cell_id
cyc0000 7            3.780611     0.236423     4.200016     2.699889
        8            3.780142     0.235713     4.199925     2.700006
cyc0100 7            3.781310     0.236284     4.199976     2.699889
        8            3.780954     0.236011     4.200045     2.699685
cyc0200 7            3.781871     0.236092     4.200016     2.700049
...                       ...          ...          ...          ...
cyc7900 8            3.806715     0.228506     4.200051     2.699931
cyc8000 7            3.803711     0.227929     4.200182     2.700055
        8            3.809843     0.225105     4.199971     2.699971
cyc8100 7            3.802249     0.230124     4.200022     2.700015
        8            3.807207     0.228295     4.199891     2.699971

                 temperature_mean  temperature_max  charge_max  charge_min  \
cycle   cell_id
cyc0000 7               40.701409        41.959953  736.154132 -730.708523
        8               40.001219        41.466637  736.965950 -727.527951
cyc0100 7               40.754810        42.022324  730.088486 -725.622450
        8               40.037383        41.529045  730.068253 -724.361775
cyc0200 7               40.753125        42.009857  726.874376 -722.198288
...                           ...              ...         ...         ...
cyc7900 8               39.938754        41.728703  573.768344 -571.643579
cyc8000 7               40.702016        42.683468  594.678431 -592.355529
        8               39.938613        41.841015  573.629564 -570.896403
cyc8100 7               40.740380        42.446453  593.100934 -591.402253
        8               39.919358        41.678761  571.523747 -569.352707

                      time_max       time_min     capacity   v_range
cycle   cell_id
cyc0000 7        735956.787089  735954.817348  1466.862655  1.500127
        8        735956.787527  735954.816280  1464.493901  1.499919
cyc0100 7        735963.928429  735961.970939  1455.710936  1.500087
        8        735963.926857  735961.966260  1454.430029  1.500360
cyc0200 7        735971.062060  735969.112122  1449.072664  1.499967
...                        ...            ...          ...       ...
cyc7900 8        736579.931370  736578.303070  1145.411923  1.500119
cyc8000 7        736588.295431  736586.621785  1187.033960  1.500127
        8        736588.250764  736586.622522  1144.525966  1.499999
cyc8100 7        736595.154703  736593.483990  1184.503186  1.500007
        8        736595.055420  736593.431805  1140.876455  1.499919

[153 rows x 12 columns]

In [30]:
features = features.drop('v_range', axis = 1)

In [31]:
features = features.sort_values(by=["cell_id","cycle"])

In [32]:
features

,,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,charge_max,charge_min,time_max,time_min,capacity
cycle,cell_id,,,,,,,,,,,
cyc0000,7,3.780611,0.236423,4.200016,2.699889,40.701409,41.959953,736.154132,-730.708523,735956.787089,735954.817348,1466.862655
cyc0100,7,3.781310,0.236284,4.199976,2.699889,40.754810,42.022324,730.088486,-725.622450,735963.928429,735961.970939,1455.710936
cyc0200,7,3.781871,0.236092,4.200016,2.700049,40.753125,42.009857,726.874376,-722.198288,735971.062060,735969.112122,1449.072664
cyc0300,7,3.782269,0.235770,4.199998,2.699911,40.817165,42.134598,722.906337,-718.684928,735979.738538,735977.796230,1441.591265
cyc0400,7,3.782829,0.235539,4.199998,2.700111,40.795414,42.109627,719.775363,-716.529429,735986.858374,735984.922265,1436.304792
...,...,...,...,...,...,...,...,...,...,...,...,...
cyc7700,8,3.808553,0.225844,4.200091,2.700012,39.935644,41.816048,576.990499,-574.471645,736566.310381,736564.675074,1151.462144
cyc7800,8,3.806736,0.228309,4.200011,2.700052,39.929936,41.678761,575.111208,-572.982491,736573.122136,736571.490995,1148.093699
cyc7900,8,3.806715,0.228506,4.200051,2.699931,39.938754,41.728703,573.768344,-571.643579,736579.931370,736578.303070,1145.411923
cyc8000,8,3.809843,0.225105,4.199971,2.699971,39.938613,41.841015,573.629564,-570.896403,736588.250764,736586.622522,1144.525966
cyc8100,8,3.807207,0.228295,4.199891,2.699971,39.919358,41.678761,571.523747,-569.352707,736595.055420,736593.431805,1140.876455

In [33]:
features.shape

(153, 11)

In [34]:
features = features.reset_index()

In [35]:
features

,cycle,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,charge_max,charge_min,time_max,time_min,capacity
0,cyc0000,7,3.780611,0.236423,4.200016,2.699889,40.701409,41.959953,736.154132,-730.708523,735956.787089,735954.817348,1466.862655
1,cyc0100,7,3.781310,0.236284,4.199976,2.699889,40.754810,42.022324,730.088486,-725.622450,735963.928429,735961.970939,1455.710936
2,cyc0200,7,3.781871,0.236092,4.200016,2.700049,40.753125,42.009857,726.874376,-722.198288,735971.062060,735969.112122,1449.072664
3,cyc0300,7,3.782269,0.235770,4.199998,2.699911,40.817165,42.134598,722.906337,-718.684928,735979.738538,735977.796230,1441.591265
4,cyc0400,7,3.782829,0.235539,4.199998,2.700111,40.795414,42.109627,719.775363,-716.529429,735986.858374,735984.922265,1436.304792
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,cyc7700,8,3.808553,0.225844,4.200091,2.700012,39.935644,41.816048,576.990499,-574.471645,736566.310381,736564.675074,1151.462144
149,cyc7800,8,3.806736,0.228309,4.200011,2.700052,39.929936,41.678761,575.111208,-572.982491,736573.122136,736571.490995,1148.093699
150,cyc7900,8,3.806715,0.228506,4.200051,2.699931,39.938754,41.728703,573.768344,-571.643579,736579.931370,736578.303070,1145.411923
151,cyc8000,8,3.809843,0.225105,4.199971,2.699971,39.938613,41.841015,573.629564,-570.896403,736588.250764,736586.622522,1144.525966
152,cyc8100,8,3.807207,0.228295,4.199891,2.699971,39.919358,41.678761,571.523747,-569.352707,736595.055420,736593.431805,1140.876455

In [36]:

features = features.sort_values(['cell_id','cycle'])


features['capacity_fade'] = features.groupby('cell_id')['capacity'].diff()


features['capacity_fade'] = features['capacity_fade'].fillna(0)

features[['cell_id','cycle','capacity','capacity_fade']].head(20)

    cell_id    cycle     capacity  capacity_fade
0         7  cyc0000  1466.862655       0.000000
1         7  cyc0100  1455.710936     -11.151719
2         7  cyc0200  1449.072664      -6.638272
3         7  cyc0300  1441.591265      -7.481399
4         7  cyc0400  1436.304792      -5.286473
5         7  cyc0500  1430.714607      -5.590185
6         7  cyc0600  1425.463226      -5.251381
7         7  cyc0700  1420.814507      -4.648719
8         7  cyc0800  1416.344547      -4.469960
9         7  cyc0900  1411.839316      -4.505231
10        7  cyc1000  1407.419670      -4.419645
11        7  cyc1100  1403.282457      -4.137214
12        7  cyc1200  1399.156235      -4.126222
13        7  cyc1300  1395.109300      -4.046935
14        7  cyc1400  1391.333305      -3.775995
15        7  cyc1600  1383.322821      -8.010484
16        7  cyc1800  1374.762764      -8.560057
17        7  cyc1900  1370.775481      -3.987284
18        7  cyc2000  1366.354664      -4.420817
19        7  cyc2100  1362.747997      -3.606667

In [37]:
features = features.drop(columns = ['charge_max', 'charge_min', 'time_max', 'time_min'])

In [38]:

features['cycle_number'] = features['cycle'].str.extract(r'(\d+)').astype(int) // 100

features = features.sort_values(['cell_id','cycle_number']).reset_index(drop=True)

In [39]:
del df
import gc
gc.collect()

19

In [40]:
initial_capacity = features.groupby('cell_id')['capacity'].transform('first')

features['SOH'] = features['capacity'] / initial_capacity

features[['cell_id','cycle','capacity','SOH']].head(20)

    cell_id    cycle     capacity       SOH
0         7  cyc0000  1466.862655  1.000000
1         7  cyc0100  1455.710936  0.992398
2         7  cyc0200  1449.072664  0.987872
3         7  cyc0300  1441.591265  0.982772
4         7  cyc0400  1436.304792  0.979168
5         7  cyc0500  1430.714607  0.975357
6         7  cyc0600  1425.463226  0.971777
7         7  cyc0700  1420.814507  0.968608
8         7  cyc0800  1416.344547  0.965560
9         7  cyc0900  1411.839316  0.962489
10        7  cyc1000  1407.419670  0.959476
11        7  cyc1100  1403.282457  0.956656
12        7  cyc1200  1399.156235  0.953843
13        7  cyc1300  1395.109300  0.951084
14        7  cyc1400  1391.333305  0.948510
15        7  cyc1600  1383.322821  0.943049
16        7  cyc1800  1374.762764  0.937213
17        7  cyc1900  1370.775481  0.934495
18        7  cyc2000  1366.354664  0.931481
19        7  cyc2100  1362.747997  0.929022

In [41]:
features = features.drop(columns = ['cycle'])

In [42]:
features

,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,capacity,capacity_fade,cycle_number,SOH
0,7,3.780611,0.236423,4.200016,2.699889,40.701409,41.959953,1466.862655,0.000000,0,1.000000
1,7,3.781310,0.236284,4.199976,2.699889,40.754810,42.022324,1455.710936,-11.151719,1,0.992398
2,7,3.781871,0.236092,4.200016,2.700049,40.753125,42.009857,1449.072664,-6.638272,2,0.987872
3,7,3.782269,0.235770,4.199998,2.699911,40.817165,42.134598,1441.591265,-7.481399,3,0.982772
4,7,3.782829,0.235539,4.199998,2.700111,40.795414,42.109627,1436.304792,-5.286473,4,0.979168
...,...,...,...,...,...,...,...,...,...,...,...
148,8,3.808553,0.225844,4.200091,2.700012,39.935644,41.816048,1151.462144,-1.576423,77,0.786253
149,8,3.806736,0.228309,4.200011,2.700052,39.929936,41.678761,1148.093699,-3.368445,78,0.783953
150,8,3.806715,0.228506,4.200051,2.699931,39.938754,41.728703,1145.411923,-2.681776,79,0.782121
151,8,3.809843,0.225105,4.199971,2.699971,39.938613,41.841015,1144.525966,-0.885957,80,0.781516
152,8,3.807207,0.228295,4.199891,2.699971,39.919358,41.678761,1140.876455,-3.649511,81,0.779024

In [43]:
features.columns

Index(['cell_id', 'voltage_mean', 'voltage_std', 'voltage_max', 'voltage_min',
       'temperature_mean', 'temperature_max', 'capacity', 'capacity_fade',
       'cycle_number', 'SOH'],
      dtype='object')

In [29]:
features.to_csv('test_final.csv', index = False)